language: python
python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true
before_install:
  - pip install -U pip
  - pip install pytest codecov
install:
  - sudo apt-get install gdal-bin libgdal-dev python-numpy python-scipy python-imaging
  - pip install rasterio>=1.0a9
  - pip install -r requirements.txt
  - pip install -e .[test]
script:
  - coverage run --source=satmeta -m py.test -v
after_success:
  - codecov
