language: python

branches:
  only:
    - master

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install python-pip
  - python3 -m pip install virtualenv
  - python3 -m venv ~/.envs/satmeta
  - source ~/.envs/satmeta/bin/activate
  - python -m pip install rasterio pillow geopandas
install:
  - source ~/.envs/satmeta/bin/activate
  - python -m pip install -e .[test]

script:
  - python -m pytest -v --color=yes --cov=satmeta

after_success:
  - codecov

notifications:
  email:
    on_failure: change
    on_success: change
